# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-ouraselain

# >> macros
# << macros

Summary:    Oura Cloud
Version:    0.4
Release:    2
Group:      Qt/Qt
License:    LICENSE
URL:        https://github.com/hsjpekka/harbour-ouraselain
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-ouraselain.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Browses the contents of Oura Cloud


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
if [ -d $HOME/.local/share/%{name}/%{name}]; then
if [ ! -d $HOME/.local/share/null.hsjpekka/%{name}]; then
mkdir $HOME/.local/share/null.hsjpekka/%{name}
fi
mv $HOME/.local/share/%{name}/%{name}/* $HOME/.local/share/null.hsjpekka/%{name}/
fi
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
